config/routes.rb
Rails.application.routes.draw do

  root :to => "questions#index"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :questions do
    resources :answers
  end

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  has_many :votes, :as => :votable

  validates :response, :presence => true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :votes, :as => :votable
  has_many :answers

  validates :content, :presence => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :questions
  has_many :votes
  has_many :answers

  has_secure_password
  validates :password, :presence => true
  validates :name, :presence => true
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :votable, polymorphic: true

  validates :tally, :presence => true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(answer_params)
    @answer.user = User.find(session[:user_id])

    if @answer.save
      flash[:notice] = "Answer successfully saved"
      redirect_to question_path(@question)
    else
      redirect_to question_path(@question)
    end
  end

  def edit
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
  end

  def update
    @answer = Answer.find(params[:id])
    @question = @answer.question
    if @answer.update(answer_params)
      flash[:notice] = "updated"
      redirect_to question_path(@question)
    else
      flash[:danger] = "fail"
      render :edit
    end
  end

private
  def answer_params
    params.require(:answer).permit(:response)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user = User.find(session[:user_id]) if session[:user_id]
    if @question.save
      flash[:notice] = "New question successfully added"
      redirect_to questions_path
    else
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
    render :edit
  end

  def update
    @question = Question.find(params[:id])
    if @question.user.id === session[:user_id] || session[:is_admin]
      if @question.update(question_params)
        flash[:notice] = "Question successfully updated!"
        redirect_to questions_path
      else
        render :edit
      end
    else
      flash[:notice] = "Buzz off! No permissions for you"
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])
    if session[:is_admin]
      @question.destroy
      flash[:notice] = "question successfully destroyed"
      redirect_to questions_path
    else
      flash[:notice] = "peon, you have no power to destroy questions!"
      redirect_to question_path(@question)
    end
  end

private
  def question_params
    params.require(:question).permit(:content)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.where(:name => params[:name].downcase).first
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      session[:is_admin] = user.admin
      flash[:alert] = "you logged in"
      redirect_to root_url
    else
      flash[:danger] = "you screwed up"
      render :new
    end
  end

  def destroy
    session[:admin] = nil
    session[:user_id] = nil
    redirect_to root_url
  end

  private
  def session_params
    params.require(:user).permit(:name, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "User added"
      redirect_to root_url
    else
      flash[:danger] = "Failed to save"
      redirect_to new_user_path
    end
  end

  def index

  end

private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/answers/_form.html.erb
<%= render "layouts/errors", :object => @answer %>
<%= form_for [@question, @answer] do |f| %>
  <%= f.label :response %>
  <%= f.text_field :response %>
  <%= f.submit %>
<% end %>

app/views/answers/edit.html.erb
<h1>Edit Answer</h1>

<%= render 'form' %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crack Overflow</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    <div class="navbar">
      <li> <a href="/">Home</a> </li>
      <% if session[:user_id] %>
      <li> <%= link_to "Log Out", session_path(0),
                :data => {:method => "delete"}%>
      </li>
      <% else %>
        <li><%= link_to "Log In", new_session_path %></li>
        <li><%= link_to "Sign Up", new_user_path %></li>
      <% end %>
    </div>
  <body>
    <p class="navbar-text pull-right">

    <p class="notice"><%= flash[:notice] %></p>
    <p class="alert"><%= flash[:alert] %></p>
    <p class="danger"><%= flash[:danger] %></p>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= render "layouts/errors", :object => @question %>

<%= form_for @question do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<%= render 'form' %>

app/views/questions/index.html.erb
<h1>CRACK OVERFLOW : Ask a Joke, Get an Punchline - Crack Up! </h1>

<ul>
  <% @questions.each do |question| %>
    <li><%= link_to question.content, question_path(question) %></li>
  <% end %>
</ul>

<hr>

<%= link_to "New Question", new_question_path %>
<%= %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

app/views/questions/show.html.erb
<%= render "layouts/errors", :object => @answer %>

<h1><%= @question.content %></h1>

<%= form_tag "/questions/#{@question.id}/answers" do |f| %>
  <%= label_tag "answer" %>
  <%= text_field_tag "answer[response]" %>
  <%= submit_tag %>
<% end %>

<% if @question.answers.any? %>
  <h4>Here are the answers/punchlines for this question?</h4>
  <ul>
    <% @question.answers.each do |answer| %>
    <li>
      <%= answer.response %>
      <% if answer.user.id === session[:user_id] || session[:is_admin] %>
        <%= link_to "Edit", edit_question_answer_path(@question, answer)%> |
        <%= link_to "Delete", question_answer_path(@question, answer),
                  :data => {:confirm => "Are you sure?",
                    :method => "delete"} %>
      <% end %>
    </li>
    <% end %>
  </ul>
<% end %>

app/views/users/new.html.erb
<%= form_for User.new do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Sign Up" %>
<% end %>